# Generated by Django 3.1.4 on 2021-04-02 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_insertion', models.DateTimeField(auto_now=True)),
                ('hybryd', models.CharField(default='hybryd', max_length=30)),
                ('herd_size', models.IntegerField(default=0)),
                ('chick_avarage_weight', models.FloatField(default=0)),
                ('age_of_the_reproductive_stock', models.CharField(default='age', max_length=30)),
                ('hatchery', models.CharField(default='hatchery', max_length=30)),
                ('current_herd_size', models.IntegerField(default=models.IntegerField(default=0))),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('cycle_day', models.IntegerField(default=0)),
                ('deads', models.IntegerField(default=0)),
                ('selection', models.IntegerField(default=0)),
                ('daily_mortality_rate', models.FloatField(default=0)),
                ('feed_consumption', models.FloatField(default=0)),
                ('wather_consumption', models.FloatField(default=0)),
                ('average_body_weight', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('medications', models.CharField(max_length=100)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_cycle.cycle')),
            ],
        ),
    ]
