# Generated by Django 3.1.4 on 2021-03-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('cycle_day', models.IntegerField(default=0)),
                ('deads', models.IntegerField(default=0)),
                ('selection', models.IntegerField(default=0)),
                ('daily_mortality_rate', models.FloatField(default=0)),
                ('feed_consumption', models.FloatField(default=0)),
                ('wather_consumption', models.FloatField(default=0)),
                ('average_body_weight', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('medications', models.CharField(max_length=100)),
            ],
        ),
    ]
