# Generated by Django 3.1.4 on 2021-04-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_cycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='medications',
            field=models.CharField(default='', max_length=100),
        ),
    ]
