# Generated by Django 3.1.4 on 2021-04-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_cycle', '0002_auto_20210402_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='medications',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
