# Generated by Django 3.1.4 on 2021-04-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_cycle', '0003_auto_20210402_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='medications',
            field=models.CharField(default='brak', max_length=100),
        ),
    ]
