# Generated by Django 3.1.4 on 2021-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_cycle', '0004_auto_20210402_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_day', models.IntegerField(default=0)),
                ('average_body_weight', models.FloatField(default=0)),
                ('daily_weight_gain', models.FloatField(default=0)),
                ('average_daily_weight_gain', models.FloatField(default=0)),
                ('feed_consumption', models.FloatField(default=0)),
                ('cumulative_feed_consumption', models.FloatField(default=0)),
                ('wather_consumption', models.FloatField(default=0)),
                ('cumulative_wather_consumption', models.FloatField(default=0)),
            ],
        ),
    ]
