# Generated by Django 3.1.4 on 2021-05-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_cycle', '0005_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='standards',
            name='feed_conversion',
            field=models.FloatField(default=0),
        ),
    ]
