# Generated by Django 3.1.4 on 2021-08-21 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_cycle', '0006_standards_feed_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('choices', models.CharField(choices=[('ST', 'Starter'), ('GR', 'Grower'), ('FR', 'Finisher')], default='ST', max_length=2)),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Slaughter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('day_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('average_weight', models.FloatField(default=0)),
                ('slaughterhouse', models.CharField(max_length=50)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_cycle.cycle')),
            ],
        ),
    ]
