# Generated by Django 3.1.4 on 2021-08-26 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production_cycle', '0007_feeddelivery_slaughter'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeddelivery',
            name='cycle',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='production_cycle.cycle'),
            preserve_default=False,
        ),
    ]
